<?php

/**
 * @file
 * BPI module.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldConfigInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bpi_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $selected_content_type = \Drupal::config('bpi.content_mapping')
    ->get('bpi_content_type');
  $user_has_access = \Drupal::currentUser()->hasPermission('bpi push content');
  if ($form_id !== 'node_' . $selected_content_type . '_edit_form' || !$user_has_access) {
    return;
  }

  $form['bpi_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('Biblioteks Produceret Indhold'),
    '#weight' => 99,
    '#attached' => [
      'library' => [
        'bpi/bpi_node_form_alter',
      ],
    ],
  ];

  $bpi_configured = bpi_service_is_configured();

  $form['bpi_settings']['send_to_bpi'] = [
    '#type' => 'checkbox',
    '#title' => t('Send to BPI'),
    '#disabled' => $bpi_configured === FALSE,
    '#default_value' => FALSE,
  ];

  $form['bpi_settings']['configurations'] = [
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => TRUE,
    '#states' => [
      'visible' => [
        ':input[name="send_to_bpi"]' => [
          'checked' => TRUE,
        ],
      ],
    ],
  ];

  $form['bpi_settings']['configurations']['dropdowns'] = [
    '#type' => 'container',
  ];

  $vocabularies = bpi_get_bpi_dictionaries();

  $categories = array_values($vocabularies['category']);
  $form['bpi_settings']['configurations']['dropdowns']['bpi_push_category'] = [
    '#type' => 'select',
    '#title' => t('Category'),
    '#options' => array_combine($categories, $categories),
    '#default_value' => 'Litteratur',
  ];

  $audiences = array_values($vocabularies['audience']);
  $form['bpi_settings']['configurations']['dropdowns']['bpi_push_audience'] = [
    '#type' => 'select',
    '#title' => t('Audience'),
    '#options' => array_combine($audiences, $audiences),
    '#default_value' => 'Voksne',
  ];

  $form['bpi_settings']['configurations']['checkboxes'] = [
    '#type' => 'container',
  ];

  $form['bpi_settings']['configurations']['checkboxes']['bpi_push_images'] = [
    '#type' => 'checkbox',
    '#title' => t('Push with images'),
    '#description' => t('You should have permission to publish the images before selecting this option.'),
    '#default_value' => FALSE,
  ];

  $form['bpi_settings']['configurations']['checkboxes']['bpi_push_ccl'] = [
    '#type' => 'checkbox',
    '#title' => t('I want to be anonymous'),
    '#description' => t('If checked, the content will be pushed as anonymous to BPI.'),
  ];

  $form['bpi_settings']['configurations']['checkboxes']['bpi_push_editable'] = [
    '#type' => 'checkbox',
    '#title' => t('Editable'),
    '#description' => t('If checked, the content will be marked as non-editable. It is not enforced, but only recommended that the content is not changed after syndication.'),
    '#default_value' => TRUE,
  ];

  $validate_handler = 'Drupal\bpi\Controller\FormHandlers::bpiPushValidate';
  $form['#validate'][] = $validate_handler;

  $submit_handler = 'Drupal\bpi\Controller\FormHandlers::bpiPushSubmit';
  $form['#submit'][] = $submit_handler;
  $form['actions']['submit']['#submit'][] = $submit_handler;
}

/**
 * Fetch dictionaries from BPI ws.
 *
 * @return array
 *   Nested array of dictionaries, keyed by dictionary
 *   type.
 */
function bpi_get_bpi_dictionaries() {
  $dictionaries = ['category' => [], 'audience' => []];

  /** @var \Drupal\bpi\Services\BpiService $bpiService */
  $bpiService = \Drupal::service('bpi.service');

  try {
    $dictionaries = $bpiService->getInstance()->getDictionaries();
  }
  catch (\Exception $e) {
    \Drupal::logger('bpi')->error($e->getMessage());
  }

  return $dictionaries;
}

/**
 * Convert node object to array structure, suitable for pushing to the well.
 *
 * @param \Drupal\node\Entity\Node $node
 *   Node object being processed.
 * @param string $category
 *   Selected category at the BPI side.
 * @param string $audience
 *   Selected audience at the BPI side.
 * @param bool $with_images
 *   Include images or not.
 * @param bool $anonymous
 *   Include author name or not.
 * @param int $editable
 *   Int 1 - to mark as editable, 0 - not editable.
 * @param bool $with_refs
 *   If TRUE ting material reference are extracted.
 *
 * @return array
 *   An array of node values, used by the BPI web service.
 *
 * @todo Add a hook allowing changing the values before they are sent to BPI.
 * @todo Split this function into smaller parts (ex: images, texts).
 */
function bpi_convert_to_bpi(Node $node, $category, $audience, $with_images = FALSE, $anonymous = FALSE, $editable = 1, $with_refs = TRUE): array {
  $bpi_content = [];

  $bpi_service_settings = \Drupal::config('bpi.service_settings');

  $bpi_content['agency_id'] = $bpi_service_settings->get('bpi_agency_id');
  $bpi_content['local_id'] = $node->id();
  $bpi_content['bpi_id'] = NULL;
  $bpi_content['url'] = Url::fromRoute('entity.node.canonical', ['node' => $node->id()], [
    'absolute' => TRUE,
    'alias' => TRUE,
  ])->toString();
  $bpi_content['data'] = '';

  $user = User::load($node->getOwnerId());
  $bpi_content['firstname'] = $user->getDisplayName();
  $bpi_content['lastname'] = '';
  $bpi_content['title'] = $node->getTitle();

  $bpi_content_mapping = \Drupal::config('bpi.content_mapping');

  $teaser_field_setting = $bpi_content_mapping->get('bpi_field_teaser');
  if (!empty($teaser_field_setting) && !empty($node->get($teaser_field_setting)->getValue())) {
    $teaser_field_values = $node->get($teaser_field_setting)->getValue();
    $teaser = !empty($teaser_field_values[0]['summary']) ? $teaser_field_values[0]['summary'] : $teaser_field_values[0]['value'];
    $bpi_content['teaser'] = html_entity_decode($teaser);
  }

  $body_field_setting = $bpi_content_mapping->get('bpi_field_body');
  if (!empty($body_field_setting) && !empty($node->get($body_field_setting)->getValue())) {
    $body_field_values = $node->get($body_field_setting)->getValue();
    $body = !empty($body_field_values[0]['value']) ? $body_field_values[0]['value'] : '';
    $bpi_content['body'] = html_entity_decode($body);

    // TODO: Image pushing/syndication is not supported for inline images.
    $bpi_content['body'] = preg_replace(
      '~(<p>)?<img.+?/>(</p>)?~is',
      '',
      $bpi_content['body']
    );
  }

  $has_teaser = !empty($bpi_content['teaser']);
  $has_body = !empty($bpi_content['body']);
  if ($has_teaser && $has_body && strcmp($bpi_content['teaser'], $bpi_content['body']) === 0) {
    $bpi_content['teaser'] = '';
  }

  $dt = new \DateTime();
  $dt->setTimestamp($node->getChangedTime());
  $bpi_content['creation'] = $dt->format(DateTime::W3C);
  $bpi_content['type'] = $node->getType();
  $bpi_content['category'] = $category;
  $bpi_content['audience'] = $audience;
  $bpi_content['related_materials'] = [];
  $bpi_content['editable'] = (int) $editable;
  $bpi_content['authorship'] = (boolean) $anonymous === FALSE;
  $bpi_content['assets'] = [];

  // Collect tags.
  $tags_field_setting = $bpi_content_mapping->get('bpi_field_tags');
  if (!empty($tags_field_setting) && !empty($node->get($tags_field_setting)->getValue())) {
    $tags_field = $node->get($tags_field_setting)->view();
    $tags = [];
    if ($tags_field['#field_type'] == 'entity_reference') {
      foreach ($tags_field['#items']->referencedEntities() as $referencedEntity) {
        $tags[] = $referencedEntity->getName();
      }
    }
    $bpi_content['tags'] = implode(',', $tags);
  }

  // Collect images.
  if ($with_images) {
    $potential_image_fields = ['image'];
    $image_fields = bpi_find_field_instances($node->getType(), $potential_image_fields);

    foreach (array_keys($image_fields) as $image_field_name) {
      if (empty($node->get($image_field_name)->getValue())) {
        continue;
      }

      $image_field = $node->get($image_field_name)->view();
      /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem $item */
      foreach ($image_field['#items'] as $item) {
        $file_uri = $item->entity->getFileUri();

        // TODO: Image pushing/syndication is broken.
        $bpi_content['assets'][] = [
          'path' => file_create_url($file_uri),
          'alt' => $item->alt ?: $item->entity->getFilename(),
          'title' => $item->title ?: $item->entity->getFilename(),
          'type' => bpi_get_image_type($image_field_name, $node),
          'name' => $item->entity->getFilename(),
          'extension' => pathinfo($file_uri, PATHINFO_EXTENSION),
        ];
      }
    }
  }

  // Collect materials.
  $materials_field_setting = $bpi_content_mapping->get('bpi_field_materials');
  if (!empty($materials_field_setting) && !empty($node->get($materials_field_setting)->getValue())) {
    $materials_field = $node->get($materials_field_setting)->view();
    $materials = [];
    // TODO: Sanitize this part.
    if ($materials_field['#field_type'] == 'entity_reference') {
      foreach ($materials_field['#items']->referencedEntities() as $referencedEntity) {
        if ($referencedEntity->getType() == 'book') {
          $faust_field = $referencedEntity->get('field_book_old_library_key');
          if ($faust_field) {
            foreach ($referencedEntity->get('field_book_old_library_key')->getValue() as $value) {
              $materials[] = $value['value'];
            }
          }
        }
        else {
          $materials[] = $referencedEntity->getTitle();
        }
      }
    }
    else {
      foreach ($materials_field['#items']->getValue() as $item) {
        $materials[] = $item['value'];
      }
    }

    // TODO:
    // Small hack for BPI validation, this might not be suitable id at all.
    array_walk($materials, function (&$v, $k) {
        $v = '870970-basis:' . $v;
    });

    $bpi_content['related_materials'] = $materials;
  }

  return $bpi_content;
}

/**
 * Track nodes push/syndication actions.
 *
 * @param int $nid
 *   Node id.
 * @param int $status
 *   BPI status.
 * @param int $bid
 *   BPI id.
 * @param array $params
 *   BPI params.
 *
 * @throws \Exception
 */
function bpi_update_syndicated($nid, $status, $bid = 0, array $params = []) {
  $fields = [
    'nid' => $nid,
    'data' => serialize($params),
    'timestamp' => \Drupal::time()->getRequestTime(),
    'status' => $status,
    'bid' => $bid,
  ];

  $query = Database::getConnection()->merge('bpi_syndicated');
  $query->condition('nid', $nid);
  $query->fields($fields);
  $query->execute();
}

/**
 * Set user friendly feedback message based on exception error codes.
 *
 * @param int $http_code
 *   Error code returned from BPI.
 */
function bpi_error_message($http_code) {
  switch ($http_code) {
    case 422:
      $msg = t('BPI: Similar resource already exists in the well.');
      break;

    case 406:
      $msg = t('BPI: Trying to syndicate content by owner who already did that is not allowed.');
      break;

    case 500;
      $msg = t('BPI: Failed to communicate with BPI service. Check your field mapping setting and/or service settings.');
      break;

    default:
      $msg = t('BPI: Generic error. Check reports for more information.');
      break;
  }

  \Drupal::messenger()->addMessage($msg, 'error');
  \Drupal::logger('bpi')->error($msg);
}

/**
 * Check that BPI service configuration have been set.
 *
 * If it have not been configured yet error message are set.
 *
 * @return bool
 *   If service is configured TRUE else FALSE is returned.
 */
function bpi_service_is_configured() {
  $settings = \Drupal::config('bpi.service_settings');

  $endpoint = $settings->get('bpi_service_url');
  $agency_id = $settings->get('bpi_agency_id');
  $api_key = $settings->get('bpi_api_key');
  $secret_key = $settings->get('bpi_secret_key');

  $configured = TRUE;

  $settings_url = Url::fromRoute('bpi.settings');
  $settings_link = Link::fromTextAndUrl(t('BPI settings'), $settings_url);
  $message = t('BPI: In order to push this content to the well, please check @settings_url.', ['@settings_url' => $settings_link->toString()]);

  if (empty($endpoint) || empty($agency_id) || empty($api_key) || empty($secret_key)) {
    \Drupal::messenger()->addMessage($message, 'error');
    $configured = FALSE;
  }

  return $configured;
}

/**
 * Implements hook_node_load().
 *
 * Enrich node object with bpi_id, if any.
 */
function bpi_node_load($nodes) {
  $node_ids = array_keys($nodes);

  $result = Database::getConnection()->select('bpi_syndicated', 'bs')
    ->fields('bs', [
      'nid',
      'bid',
    ])
    ->condition('nid', $node_ids, 'IN')
    ->execute()
    ->fetchAllAssoc('nid');

  foreach ($nodes as $nid => &$node) {
    if (isset($result[$nid])) {
      $node->bpi_id = $result[$nid]->bid;
    }
  }
}

/**
 * Get a list of fields, for a certain node type.
 *
 * Simplifies and filters the output of the core field_info_instances()
 * function.
 *
 * Filtering means that we do not want text values into image fields, etc.
 *
 * @param string $node_type
 *   Node type machine name, whose fields list is expected.
 * @param array $allowed_types
 *   Filter by these instance types.
 *
 * @return array
 *   An array with the fields, for the specified node type.
 */
function bpi_find_field_instances($node_type, array $allowed_types): array {
  if (empty($node_type)) {
    return [];
  }

  $entityManager = \Drupal::service('entity_field.manager');
  $node_fields = array_filter($entityManager->getFieldDefinitions('node', $node_type), function ($field_definition) {
    return $field_definition instanceof FieldConfigInterface;
  });

  $fields = [];
  /** @var \Drupal\field\Entity\FieldConfig $field */
  foreach ($node_fields as $field) {
    if (in_array($field->getType(), $allowed_types)) {
      $fields[$field->getName()] = $field->getLabel();
    }
  }

  return $fields;
}

/**
 * Compute the image type from a field name on a node.
 *
 * TODO: Purpose of this is unknown.
 *
 * @param string $image_field_name
 *   The image field name.
 * @param \Drupal\node\Entity\Node $node
 *   The node.
 *
 * @return null|string
 *   The image type.
 */
function bpi_get_image_type($image_field_name, Node $node) {
  /*
   * We assume that the image type is the last part of the field name, i.e.
   *   field_{{node type}}_{{image type}}
   */
  $pattern = '/field_' . preg_quote($node->getType(), '/') . '_(?<image_type>.+)/';
  if (preg_match($pattern, $image_field_name, $matches)) {
    return $matches['image_type'];
  }
  return NULL;
}
