# itk-version: 3.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    image: itkdev/php7.4-fpm:alpine
    restart: unless-stopped
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=128M
      - COMPOSER_VERSION=2
    depends_on:
      - memcached
    volumes:
      - .:/app

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '8080'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/app:rw
    labels:
      - "traefik.enable=false"
      - "traefik.docker.network=frontend"

  memcached:
    image: 'memcached:latest'
    restart: unless-stopped
    networks:
      - app
    environment:
      - MEMCACHED_CACHE_SIZE=64
