# itk-version: 2.0.1
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryptionn.
    labels:
      com.symfony.server.service-prefix: "DATABASE"

  phpfpm:
    image: itkdev/php7.4-fpm:latest
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
    depends_on:
      - mariadb
      - memcached
    volumes:
      - nfsApp:/app:delegated

  littnginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - nfsApp:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.nginx_${COMPOSE_PROJECT_NAME}.rule=Host(`nginx.${COMPOSE_DOMAIN}`)"

  varnish:
    image: 'wodby/varnish:6'
    ports:
      - '6081'
    networks:
      - app
      - frontend
    depends_on:
      - littnginx
    environment:
      VARNISHD_VCL_SCRIPT: /etc/varnish/litt.vcl
      VARNISH_SECRET: eca2b7c263eae74c0d746f147691e7ce
    volumes:
      - ${PWD}/.docker/litt.vcl:/etc/varnish/litt.vcl:ro
      - nfsApp:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.port=6081"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  es:
    image: elasticsearch:6.7.0
    networks:
      - app
    environment:
      - discovery.type=single-node
    ports:
      - "9200"
      - "9300"

  memcached:
    image: 'memcached:latest'
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
      - frontend
    ports:
      - "1025"
      - "8025"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}Mailhog.rule=Host(`mailhog-${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}Mailhog.loadbalancer.server.port=8025"

volumes:
  # Named volume requires that you have NFS shares enabled (performance boost on Macs).
  # Use `itkdev-docker-compose nfs:enable` to enable NFS shares. If you don't want to use it remove it from here and
  # change the volume mapping to use normal shares in the containers. See
  # https://sean-handley.medium.com/how-to-set-up-docker-for-mac-with-native-nfs-145151458adc
  nfsApp:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$PWD"
