<?php

/**
 * @file
 * Contains hooks related to lit_og_image module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\lit_og_image\Helper\Helper;

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 *   The form to alter.
 * @param FormStateInterface $form_state
 *   The state of the form.
 * @param string $form_id
 *   The form id.
 *
 * @see \Drupal\lit_og_image\Helper\Helper::alterForm()
 */
function lit_og_image_form_node_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service(Helper::class)->alterForm($form);
}

/**
 * Implements hook_page_attachments().
 *
 * @param array $page
 *   The current page.
 *
 * @see \Drupal\lit_og_image\Helper\Helper::pageAttachment()
 */
function lit_og_image_page_attachments(array &$page) {
  Drupal::service(Helper::class)->pageAttachment($page);
}
